<?php

namespace AppBundle\Repository;

/**
 * MmfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MmfRepository extends \Doctrine\ORM\EntityRepository
{
}
